### ISSUE TITLE
No tags

### ISSUE THREAD

**Issue by aymeric-ledizes** [cloudprober/helm-charts#23]
Currently, there are only 2 branches `gh-pages` and `main`.
It would be nice to have tags to control the deployment of this chart 🙏

**Comment by manugarg** [comment]
Good point. Thanks for filing this @aymeric-ledizes.

Since we use Github action workflow to create a new release, we can possibly just create a tag from that workflow itself.

Note: To automate the process, chart version is automatically calculated from the chart's base version and Cloudprober version.

**Comment by manugarg** [comment]
It's done:
https://github.com/cloudprober/helm-charts/commit/2ec691bbc6f8405ff5b7838a1736dace57516f7e

**Comment by aymeric-ledizes** [comment]
Awesome thanks!
